version: '2'
services:
    sparkhipster-app:
        image: sparkhipster
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=sparkhipster-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    sparkhipster-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: sparkhipster-cassandra
    sparkhipster-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=sparkhipster-cassandra
    sparkhipster-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: sparkhipster-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
