version: '2'
services:
    sparkhipster-cassandra:
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/sparkhipster/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
        environment:
            - MAX_HEAP_SIZE=1g
            - HEAP_NEWSIZE=256M
    sparkhipster-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: sparkhipster-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
